### ISSUE TITLE
Viterbi.java第一个函数路径优化

### ISSUE THREAD

**Issue by weiyinfu** [hankcs/Viterbi#5]
现在代码中路径的保存是通过arrayCopy实现的，这样会导致费很多内存
public static int[] compute(int[] observation, int[] states, double[] start_p, double[][] trans_p, double[][] emit_p)

可以改为只使用一个二维数组来实现，每个状态记录它的上一状态

**Comment by hankcs** [comment]
是的，可以参考HanLP的ViterbiDecode：https://github.com/hankcs/HanLP/blob/master/src/main/java/com/hankcs/hanlp/model/perceptron/model/LinearModel.java#L273
